# Generated by Django 5.0 on 2023-12-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('board_name', models.CharField(max_length=50)),
                ('contents', models.TextField()),
            ],
        ),
    ]
